name: Build and Publish Backend

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_TOKEN }}

    - name: Install Dependencies
      run: npm install

    - name: Build Binaries
      run: npm run build

    - name: Build Docker Image
      run: |
        version=$(echo "${{ github.ref }}" | cut -d'/' -f 3)
        docker build -t fmronin/community-saver-docker .
        docker build -t fmronin/community-saver-docker:"${version}" .
        docker push fmronin/community-saver-docker
        docker push fmronin/community-saver-docker:"${version}"
    